name: qbf-logic
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - requests>=2.28.0
      - python-dotenv>=1.0.0
      - dataclasses-json>=0.5.7
      - pytest>=7.0.0
      - pytest-cov>=4.0.0
      - black>=22.0.0
      - flake8>=5.0.0
      - jupyter>=1.0.0
      - ipykernel>=6.0.0
